name: Dev workflow

on: [push]

jobs:
  example:
    name: Dev Terragrunt interaction
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.1.0
        with:
          terragrunt_version: 0.38.9
      - name: Interact with Terragrunt
        run: terragrunt --version